### ISSUE TITLE
Error loading MouseHunt Improved

### ISSUE THREAD

**Issue by ljmaroto** [MHCommunity/mousehunt-improved#426]
Started happening on the 3 computers I use on August 7, 2024. 
Chrome version: 127.0.6533.100 (Official Build) (64-bit)
Mousehunt improved version: 0.54.4

```
Cannot read properties of undefined (reading 'id')

TypeError: Cannot read properties of undefined (reading 'id')
    at getLegacyHudHtml (chrome-extension://fgjkidgknmkhnbeobehlfabjbignhkhm/main.js:24848:105)
    at replaceStatsBar (chrome-extension://fgjkidgknmkhnbeobehlfabjbignhkhm/main.js:24920:85)
    at chrome-extension://fgjkidgknmkhnbeobehlfabjbignhkhm/main.js:24966:11
    at Generator.next (<anonymous>)
    at chrome-extension://fgjkidgknmkhnbeobehlfabjbignhkhm/main.js:70:63
    at new Promise (<anonymous>)
    at __async (chrome-extension://fgjkidgknmkhnbeobehlfabjbignhkhm/main.js:54:12)
    at Object.init49 [as load] (chrome-extension://fgjkidgknmkhnbeobehlfabjbignhkhm/main.js:24955:22)
    at Object.<anonymous> (chrome-extension://fgjkidgknmkhnbeobehlfabjbignhkhm/main.js:39680:35)
    at Generator.next (<anonymous>)
```

Is the solution to go to an earlier version?

**Comment by bradp** [comment]
Fixed in 0.55.0
